export const phrases = [
    "The sun set fast, and the stars lit up the dark, vast sky in a calm glow.",
    "A soft wind blew past the hills, its touch light and cool on the skin of all.",
    "She sang a sweet tune, her voice pure and soft as the birds sang in the trees.",
    "The waves hit the shore, foam bright and white, as the day came to a calm end.",
    "Time is a gift we must use well; once gone, it will not come back to us.",
    "He held the old map in his hand, its lines bold and paths clear to the eye.",
    "Hope is a flame that burns in the dark, its light warm and sure in hard times.",
    "The path was long, but the view at the top made the walk worth each step taken.",
    "The sky was red, and the sun hung low as if it did not want to leave.",
    "Peace comes not from the loud sound of war, but from the soft sound of kind hearts.",
    "Books tell tales of old, with words that last far past the lives of those who wrote them.",
    "The lake was still, a mirror that held the sky and trees in its calm, cool face.",
    "Love is felt in small acts of care, a hug, a kind word, or a warm smile.",
    "The cold air bit at his face, but his will was strong, and he did not stop.",
    "A child's laugh is pure and bright, a gift that brings joy to all who hear it.",
    "The quick brown fox jumps over the lazy dog, effortlessly agile.",
    "Life is what happens when you're busy making other plans, true as ever.",
    "To be or not to be, that is the ultimate question pondering existence itself.",
    "All that glitters is not gold, yet the allure is often deceptive and compelling.",
    "Do or do not, there is no try, a lesson in commitment and resolve.",
    "The gentle rain fell softly on the leaves, creating a rhythmic melody that soothed the weary soul.",
    "She walked through the quiet forest, her footsteps blending with the whispers of the rustling trees around her.",
    "Hope is a fragile yet powerful force, lighting the way even when the world feels dark and empty.",
    "The ocean stretched endlessly to the horizon, its waves crashing with a steady rhythm against the rocky shore.",
    "Under the vast night sky, he felt both insignificant and connected to something infinitely greater than himself.",
    "Dreams give us a glimpse of what could be, inspiring us to reach beyond our current limitations and fears.",
    "The warm glow of the fire danced across their faces, bringing comfort and light to the cold night.",
    "A moment of silence can say more than a thousand words, speaking volumes in its profound simplicity and truth.",
    "Through hard work and persistence, great things are achieved, proving that effort and determination lead to lasting success.",
    "The old house creaked with each gust of wind, as if it had secrets waiting to be discovered inside.",
    "Friendship grows in small moments of shared laughter, mutual support, and the comfort of simply being there for each other.",
    "The morning sun rose slowly, painting the sky in vibrant hues of orange, pink, and gold as the world awoke.",
    "Life’s most valuable lessons are often learned in silence, through quiet reflection and the wisdom gained from experience.",
    "He stood on the mountain peak, taking in the breathtaking view and feeling an overwhelming sense of accomplishment and peace.",
    "Kindness, though small in gesture, has a ripple effect, touching hearts and inspiring others to spread love and compassion.",
    "Actions speak louder than words, as deeds are the true measure of intent and character.",
    "A picture is worth a thousand words, telling stories and emotions without uttering a single syllable.",
    "Better late than never, for even a delayed effort is better than inaction altogether.",
    "Practice makes perfect, a mantra that encourages persistence and learning through repeated experience and dedication.",
    "When in Rome, do as the Romans do, adapting to local customs and traditions in harmony.",
    "The pen is mightier than the sword, as ideas can shape minds and change the world.",
    "A journey of a thousand miles begins with a single step, underscoring the importance of starting something meaningful.",
    "No man is an island, emphasizing our interdependence and the power of community and connection.",
    "The stars shone brightly in the midnight sky, casting a silver glow across the tranquil landscape as the world slept peacefully.",
    "She walked slowly along the narrow cobblestone streets, the faint aroma of fresh bread wafting from nearby bakeries and filling the crisp morning air.",
    "In the end, it’s not the years in your life that count but the life in your years, the experiences, and the memories cherished.",
    "Through trials and tribulations, one discovers resilience and strength within, an enduring testament to the human spirit's unyielding nature.",
    "As the sun dipped below the horizon, painting the sky with hues of orange and purple, the world seemed to hold its breath in awe.",
    "Success is not final, failure is not fatal; it is the courage to continue that counts, driving us forward against the odds.",
    "Each moment we live offers a choice: to embrace the present fully, to learn from the past, and to step boldly into the future with hope and determination.",
    "Happiness can be found even in the darkest of times if one only remembers to turn on the light, a powerful reminder of hope and resilience.",
    "The road to success is never a straight path; it is filled with twists, turns, and occasional setbacks that test determination and perseverance.",
    "In every walk with nature, one receives far more than he seeks, finding peace, inspiration, and a profound connection to the world around us.",
    "Kindness is a language that the deaf can hear and the blind can see, a universal gesture that bridges gaps and brings humanity closer together.",
    "Even the smallest act of caring for another person is like a drop of water; it will make ripples throughout the entire pond of humanity.",
    "Time flies like an arrow, but fruit flies like a banana, reminding us to appreciate the moments while maintaining a sense of humor about life.",
    "The great oak tree that stands tall today began as a small seed buried in the earth, a testament to patience and the power of growth.",
    "Every morning is a new beginning, a fresh opportunity to chase dreams, mend mistakes, and build the life you truly desire with purpose and determination.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away, the magical instances that define us.",
    "The library was a sanctuary of knowledge, each book a portal to another world, filled with adventures, lessons, and characters waiting to come alive in imagination.",
    "As the rain poured down, cleansing the earth and filling the air with its soothing rhythm, it seemed to wash away the worries of the day.",
    "With every word, the storyteller painted vivid images, weaving tales of courage, love, and adventure that captivated hearts and minds long after the tale was told.",
    "Gratitude turns what we have into enough, and even more, it unlocks the fullness of life and fosters joy in the simplest of moments.",
    "Dreams are the whispers of the soul, urging us to reach beyond the ordinary and embrace the extraordinary potential that lies within each of us.",
    "The world is full of magic things, patiently waiting for our senses to grow sharper, and for us to rediscover the wonder that surrounds us.",
    "A gentle breeze carried the scent of blooming flowers, rustling leaves in its path, and whispering secrets of the changing season to anyone willing to listen.",
    "When you focus on what you have, you gain a sense of abundance; when you focus on what you lack, life feels empty and incomplete.",
    "Courage does not always roar; sometimes it is the quiet voice at the end of the day saying, 'I will try again tomorrow,' a quiet resolve.",
    "The stars are the timeless witnesses of history, silently observing the rise and fall of civilizations, the hopes and dreams of countless generations before us.",
    "To love and be loved is to feel the sun from both sides, a warmth that fills the heart and illuminates even the darkest corners of life.",
    "The world is a canvas, and we are all artists painting our unique stories upon it, each stroke adding to the grand masterpiece of existence.",
    "Happiness is not found in material wealth or fleeting pleasures but in the simple joys of life, shared with those who mean the most to us.",
    "With every sunrise, the earth reminds us that each day is a new opportunity to start over, to grow, and to strive for a better version of ourselves.",
    "She sat by the window, watching raindrops race down the glass as thunder rolled in the distance, her thoughts a tangled web of memories and dreams.",
    "Kindness is a language that transcends barriers, a universal expression of compassion and humanity that can brighten even the darkest of days.",
    "The forest was alive with the sounds of chirping birds, rustling leaves, and the occasional rustle of small creatures scurrying through the underbrush.",
    "In a small village tucked away in the mountains, where the air was crisp and the stars shone like diamonds, life moved at a pace all its own.",
    "Courage is not the absence of fear but the determination to face it head-on, to take that leap into the unknown and trust in your strength to endure.",
    "Under the blanket of night, the sea glistened with moonlight, waves whispering secrets of a world unseen and mysteries yet to be discovered.",
    "The stories we tell shape the way we see the world, and in sharing them, we connect, inspire, and understand one another in profound ways.",
    "Time flows like a river, carrying us forward through the currents of change and growth, never allowing us to step into the same moment twice.",
    "On the edge of the cliff, the wind howled around him as he gazed at the endless horizon, feeling both infinitely small and inexplicably free.",
    "In every leaf that falls, there is a reminder of the cyclical nature of life, a quiet acceptance of endings that make way for new beginnings.",
    "The library was a haven of stories and knowledge, its shelves filled with the whispers of countless voices waiting to be heard by those who dared to listen.",
    "True strength lies not in the ability to dominate but in the capacity for empathy, understanding, and lifting others when they are at their lowest.",
    "As the train sped through golden fields, the rhythmic clatter of wheels on the track blended with the distant hum of an approaching storm.",
    "Dreams are not merely figments of imagination; they are the seeds of ambition, watered by persistence and nurtured with hope, growing into reality over time.",
    "The garden bloomed in a riot of colors, each flower a testament to the beauty of patience, care, and the cycle of nature’s miracles.",
    "History is written in the footsteps of those who dared to challenge the status quo, blazing trails where none existed before and leaving legacies that inspire."
];
